version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.0.7
    - 11.1.2
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.8
  - dependency-name: "@angular/language-service"
    versions:
    - 11.0.8
    - 11.1.2
    - 11.2.2
    - 11.2.3
    - 11.2.9
  - dependency-name: karma
    versions:
    - 5.2.3
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.2
    - 3.6.3
    - 3.6.4
    - 3.6.6
    - 3.6.7
  - dependency-name: firebase-tools
    versions:
    - 9.2.1
    - 9.2.2
    - 9.3.0
    - 9.5.0
    - 9.6.1
    - 9.8.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
