{
  "language": "node_js",
  "node_js": "8",
  "before_script": [
    "npm install -g @angular/cli",
    "npm install -g jest",
    "npm install -g codecov",
    "npm install -g coveralls"
  ],
  "script": [
    "lerna bootstrap",
    "lerna exec -- npm run build",
    "lerna exec -- npm run test"
  ],
  "after_success": [
    "lerna exec -- npm run codecov"
  ]
}