# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/pendragon

    steps:
      - checkout
      - run:
          name: Update lerna
          command: 'sudo npm install -g lerna'
      - run:
          name: Update angular-cli
          command: 'sudo npm install -g @angular/cli'
      - run:
          name: Update typescript
          command: 'sudo npm install -g typescript'
      - run:
          name: Update tslint
          command: 'sudo npm install -g tslint'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Bootstrap project
          command: lerna bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build project
          command: 'lerna exec -- npm run build'
  test:
    docker:
      - image: circleci/node:8.10

    steps:
      - checkout
      - run:
          name: Update lerna
          command: 'sudo npm install -g lerna'
      - run:
          name: Update angular-cli
          command: 'sudo npm install -g @angular/cli'
      - run:
          name: Update jest
          command: 'sudo npm install -g jest'
      - run:
          name: Update codecov
          command: 'sudo npm install -g codecov'
      - run:
          name: Update codecov
          command: 'sudo npm install -g coveralls'
      - run:
          name: Test
          command: lerna exec -- npm run test
      - store_artifacts:
          path: packages/*/coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
